import { Platform, Share } from 'react-native';

/**
 * Data Export Service for Gentle Reminder.
 *
 * Generates and shares patient cognitive health reports in
 * multiple formats (JSON, CSV, summary text).
 * Uses the native share sheet for delivery.
 */

export interface ExportableData {
  patientName: string;
  patientId: string;
  dateRange: { from: string; to: string };
  sessions: {
    date: string;
    score: number;
    duration: number;
    exercisesCompleted: number;
    domains: Record<string, number>;
  }[];
  medications: {
    name: string;
    dosage: string;
    adherencePercent: number;
  }[];
  cognitiveScores: {
    date: string;
    overall: number;
    orientation: number;
    memory: number;
    attention: number;
    language: number;
    visuospatial: number;
  }[];
  moodHistory: {
    date: string;
    mood: string;
  }[];
}

// Demo data for export
function getDemoData(): ExportableData {
  const now = new Date();
  const scores = [];
  const sessions = [];
  for (let i = 29; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    const dateStr = date.toISOString().split('T')[0];
    const baseScore = 70 + Math.sin(i / 5) * 8 + Math.random() * 5;
    scores.push({
      date: dateStr,
      overall: Math.round(baseScore),
      orientation: Math.round(baseScore + Math.random() * 10),
      memory: Math.round(baseScore - Math.random() * 10),
      attention: Math.round(baseScore + Math.random() * 5),
      language: Math.round(baseScore - Math.random() * 5),
      visuospatial: Math.round(baseScore + Math.random() * 8),
    });
    if (i % 2 === 0) {
      sessions.push({
        date: dateStr,
        score: Math.round(baseScore),
        duration: 8 + Math.floor(Math.random() * 7),
        exercisesCompleted: 6 + Math.floor(Math.random() * 3),
        domains: { orientation: 0.85, memory: 0.7, attention: 0.75, language: 0.8, visuospatial: 0.72 },
      });
    }
  }

  return {
    patientName: 'Margaret Wilson',
    patientId: 'demo-patient-margaret',
    dateRange: { from: scores[0].date, to: scores[scores.length - 1].date },
    sessions,
    medications: [
      { name: 'Donepezil', dosage: '10mg daily', adherencePercent: 95 },
      { name: 'Memantine', dosage: '10mg twice daily', adherencePercent: 88 },
      { name: 'Vitamin D', dosage: '2000 IU daily', adherencePercent: 92 },
    ],
    cognitiveScores: scores,
    moodHistory: [
      { date: scores[scores.length - 1].date, mood: 'calm' },
      { date: scores[scores.length - 2].date, mood: 'happy' },
      { date: scores[scores.length - 3].date, mood: 'calm' },
    ],
  };
}

class DataExportService {
  private static instance: DataExportService;

  private constructor() {}

  static getInstance(): DataExportService {
    if (!DataExportService.instance) {
      DataExportService.instance = new DataExportService();
    }
    return DataExportService.instance;
  }

  /**
   * Generate and share a weekly summary report (text format).
   */
  async shareWeeklyReport(): Promise<boolean> {
    const data = getDemoData();
    const recentScores = data.cognitiveScores.slice(-7);
    const recentSessions = data.sessions.slice(-4);
    const avgScore = Math.round(recentScores.reduce((s, r) => s + r.overall, 0) / recentScores.length);

    let report = `📊 GENTLE REMINDER — Weekly Report\n`;
    report += `Patient: ${data.patientName}\n`;
    report += `Period: ${recentScores[0].date} to ${recentScores[recentScores.length - 1].date}\n`;
    report += `\n━━━ Cognitive Summary ━━━\n`;
    report += `Average Score: ${avgScore}/100\n`;
    report += `Sessions Completed: ${recentSessions.length}\n`;
    report += `\n━━━ Domain Breakdown ━━━\n`;
    const latest = recentScores[recentScores.length - 1];
    report += `Orientation: ${latest.orientation}/100\n`;
    report += `Memory: ${latest.memory}/100\n`;
    report += `Attention: ${latest.attention}/100\n`;
    report += `Language: ${latest.language}/100\n`;
    report += `Visuospatial: ${latest.visuospatial}/100\n`;
    report += `\n━━━ Medication Adherence ━━━\n`;
    data.medications.forEach((m) => {
      report += `${m.name} (${m.dosage}): ${m.adherencePercent}%\n`;
    });
    report += `\n— Generated by Gentle Reminder\n`;

    return this.shareText('Weekly Cognitive Report', report);
  }

  /**
   * Export full history as JSON and share.
   */
  async exportFullHistory(): Promise<boolean> {
    const data = getDemoData();
    const json = JSON.stringify(data, null, 2);
    return this.shareText('Gentle Reminder - Full Data Export', json);
  }

  /**
   * Export as CSV format.
   */
  async exportAsCSV(): Promise<boolean> {
    const data = getDemoData();
    let csv = 'Date,Overall,Orientation,Memory,Attention,Language,Visuospatial\n';
    data.cognitiveScores.forEach((s) => {
      csv += `${s.date},${s.overall},${s.orientation},${s.memory},${s.attention},${s.language},${s.visuospatial}\n`;
    });
    return this.shareText('Cognitive Scores Export (CSV)', csv);
  }

  private async shareText(title: string, content: string): Promise<boolean> {
    try {
      if (Platform.OS === 'web') {
        // Web: use clipboard or download
        if (typeof navigator !== 'undefined' && navigator.clipboard) {
          await navigator.clipboard.writeText(content);
        }
        return true;
      }

      const result = await Share.share({
        title,
        message: content,
      });

      return result.action === Share.sharedAction;
    } catch {
      return false;
    }
  }
}

export const dataExportService = DataExportService.getInstance();
export { DataExportService };
