import { Router } from 'express';
import authRoutes from './auth.routes.js';
import usersRoutes from './users.routes.js';
import patientsRoutes from './patients.routes.js';
import caregiversRoutes from './caregivers.routes.js';
import familiesRoutes from './families.routes.js';
import sessionsRoutes from './sessions.routes.js';
import exercisesRoutes from './exercises.routes.js';
import memoriesRoutes from './memories.routes.js';
import analyticsRoutes from './analytics.routes.js';
import voiceRoutes from './voice.routes.js';
import wearablesRoutes from './wearables.routes.js';
import medicationsRoutes from './medications.routes.js';
import messagesRoutes from './messages.routes.js';
import reportsRoutes from './reports.routes.js';
import biomarkersRoutes from './biomarkers.routes.js';
import fhirRoutes from './fhir.routes.js';
import tenantsRoutes from './tenants.routes.js';
import surveillanceRoutes from './surveillance.routes.js';
import notificationsRoutes from './notifications.routes.js';
import healthRoutes from './health.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/patients', patientsRoutes);
router.use('/caregivers', caregiversRoutes);
router.use('/families', familiesRoutes);
router.use('/sessions', sessionsRoutes);
router.use('/exercises', exercisesRoutes);
router.use('/memories', memoriesRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/voices', voiceRoutes);
router.use('/wearables', wearablesRoutes);
router.use('/medications', medicationsRoutes);
router.use('/messages', messagesRoutes);
router.use('/reports', reportsRoutes);
router.use('/biomarkers', biomarkersRoutes);
router.use('/fhir', fhirRoutes);
router.use('/tenants', tenantsRoutes);
router.use('/surveillance', surveillanceRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/health', healthRoutes);

export default router;
