apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: gentle-reminder
  labels:
    app.kubernetes.io/name: ai
    app.kubernetes.io/part-of: gentle-reminder
    app.kubernetes.io/component: ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
