/**
 * IP Portfolio — single source of truth for the 23 patentable innovations.
 * Populated from docs/ip/*.md files (public-safe content only).
 * Trade-secret numerical values are NOT exposed here.
 */

export type IPTier = 1 | 2 | 3;
export type IPCategory = 'algorithm' | 'system' | 'ux' | 'clinical' | 'compliance';
export type FilingStatus = 'draft' | 'filed' | 'pending' | 'granted';

export interface IPEntry {
  id: string;
  slug: string;
  tier: IPTier;
  title: string;
  shortTitle: string;
  category: IPCategory;
  headline: string;
  problemSolved: string;
  novelMethod: string;
  priorArtDiff: string;
  commercialApplications: string[];
  filingStatus: FilingStatus;
  filingDocket: string;
  relatedIPs: string[];
  codeReference: {
    file: string;
    function: string;
  };
  estimatedValuation: string;
}

export const IP_PORTFOLIO: IPEntry[] = [
  {
    id: '01',
    slug: 'gentle-feedback-scoring',
    tier: 1,
    title: 'Three-State Positive-Only Feedback System for Cognitive Assessment',
    shortTitle: 'Gentle Feedback Scoring',
    category: 'algorithm',
    headline: 'Architecturally guarantees zero negative feedback reaches the patient, while preserving granular data for clinicians.',
    problemSolved: 'Traditional cognitive tests (MMSE, MoCA) produce pass/fail feedback that triggers anxiety, agitation, and session abandonment in dementia populations.',
    novelMethod: 'All patient responses map to one of three positive-framed states: CELEBRATED, GUIDED, or SUPPORTED. A separate clinician data channel preserves raw correctness, response time, and error metrics. A session-level fatigue detector shortens sessions without notifying the patient.',
    priorArtDiff: 'No prior art provides architectural separation of patient feedback from clinician data. Akili, Lumosity, Cogstate, and Neurotrack all display numeric scores or binary feedback to patients.',
    commercialApplications: [
      'FDA 510(k) cleared digital cognitive assessment',
      'Pharma clinical trial endpoint measurement',
      'In-home patient self-assessment',
      'Licensable scoring methodology for competitive platforms',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-01-PROV',
    relatedIPs: ['02', '12', '19'],
    codeReference: {
      file: 'packages/cognitive-engine/src/scoring/gentle-scorer.ts',
      function: 'calculateSessionScores()',
    },
    estimatedValuation: '$3M-$8M',
  },
  {
    id: '02',
    slug: 'adaptive-difficulty-engine',
    tier: 1,
    title: 'Asymmetric Comfort-Zone Adaptive Difficulty for Dementia',
    shortTitle: 'Adaptive Difficulty Engine',
    category: 'algorithm',
    headline: 'Drops difficulty in 2 failures; requires 4 consecutive successes to advance. Targets a 70–85% success comfort zone.',
    problemSolved: 'Symmetric adaptive testing algorithms cause frustration cascades in dementia patients. Standard CAT assumes improving learners; dementia populations have declining memory.',
    novelMethod: 'Asymmetric thresholds: difficulty drops on 2 consecutive incorrect responses but only advances after 4 consecutive correct plus 85%+ average. Target success zone 70-85% (vs standard 50-75%). Five discrete difficulty levels parameterize option count, hint availability, time limit, and prompt complexity.',
    priorArtDiff: 'Akili AKL-T01 (US 9,610,051), Lumosity (US 9,536,427), and IRT-based CAT use symmetric thresholds and aim for 50-75% success. None handle dementia-specific frustration triggers.',
    commercialApplications: [
      'Cognitive training products for dementia',
      'Pharma co-development for cognitive maintenance protocols',
      'Licensing to educational technology for elderly populations',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-02-PROV',
    relatedIPs: ['01', '03'],
    codeReference: {
      file: 'packages/cognitive-engine/src/scoring/adaptive-difficulty.ts',
      function: 'calculateDifficulty()',
    },
    estimatedValuation: '$2M-$5M',
  },
  {
    id: '03',
    slug: 'dementia-spaced-repetition',
    tier: 1,
    title: 'Dementia-Adapted Spaced Repetition',
    shortTitle: 'Dementia-Adapted SM-2',
    category: 'algorithm',
    headline: 'Modified SuperMemo-2 with 5 dementia-specific adaptations: 7-day max interval, no-reset-on-failure, gentler ease factor.',
    problemSolved: 'SM-2 and Anki use 365+ day intervals and reset cards on failure — both catastrophic for progressive cognitive decline.',
    novelMethod: '(1) Maximum interval capped at 7 days (vs SM-2 365+); (2) failure halves the interval instead of resetting; (3) minimum interval of 1 hour; (4) ease factor floor at 1.5 (vs SM-2 1.3); (5) three-phase initial spacing (1h→6h→computed).',
    priorArtDiff: 'SM-2 (Wozniak 1990), Anki, and Duolingo HLR (US 9,904,676) all assume improving learners. No prior art adapts spaced repetition for progressive cognitive decline.',
    commercialApplications: [
      'Memory reinforcement in anti-amyloid therapy programs (Leqembi, Aduhelm)',
      'Standalone dementia memory training apps',
      'Licensing to pharma companion apps',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-03-PROV',
    relatedIPs: ['02'],
    codeReference: {
      file: 'packages/cognitive-engine/src/exercises/spaced-repetition.ts',
      function: 'processReview()',
    },
    estimatedValuation: '$1.5M-$4M',
  },
  {
    id: '04',
    slug: 'multimodal-cognitive-state',
    tier: 1,
    title: 'Multimodal Cognitive State Classifier with Weight Redistribution',
    shortTitle: 'Multimodal State Classifier',
    category: 'algorithm',
    headline: 'Classifies 7 cognitive states from speech, behavior, and biometric signals with automatic weight redistribution when sensors fail.',
    problemSolved: 'Prior multimodal classifiers fail silently when a signal source is unavailable. In dementia care, patients may not always speak, wear wearables, or be observed.',
    novelMethod: 'Default weights speech 0.45, behavior 0.30, biometric 0.25. When a source is missing, weights are proportionally redistributed. Confidence combines absolute score (60%) + separation from second-best (40%). Trigger source identifies which signal dominated the classification.',
    priorArtDiff: 'Affectiva (US 8,219,438), Beyond Verbal (US 10,152,988), and IBM Watson use fixed weights and single-factor confidence.',
    commercialApplications: [
      'Adaptive interaction across voice companion, music therapy, and session modules',
      'Licensing to care facility monitoring systems',
      'Foundation for behavioral health AI products',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-04-PROV',
    relatedIPs: ['05', '19'],
    codeReference: {
      file: 'packages/cognitive-state/src/CognitiveStateEngine.ts',
      function: 'classifyState()',
    },
    estimatedValuation: '$2M-$5M',
  },
  {
    id: '05',
    slug: 'dementia-speech-emotion',
    tier: 1,
    title: 'Dementia-Specific Speech Emotion Detection',
    shortTitle: 'Dementia Speech Emotion',
    category: 'algorithm',
    headline: 'Combines dementia-specific keyword dictionaries with elderly-tuned acoustic feature thresholds to detect 6 emotion states.',
    problemSolved: 'General emotion detectors (Beyond Verbal, IBM Watson) are trained on healthy adult speech. They miss dementia-specific markers and misclassify slow elderly speech as sadness.',
    novelMethod: 'Dementia keyword dictionaries (e.g., confused: "don\'t understand", "where am I", "forgot") plus audio thresholds tuned for elderly: >170 wpm → +0.3 anxiety, <80 wpm → +0.3 sadness, pitch variance >50 Hz → anxiety + agitation, pause >1200ms → confusion + sadness.',
    priorArtDiff: 'No prior art combines dementia keyword dictionaries with elderly-tuned audio feature thresholds.',
    commercialApplications: [
      'Licensing to voice AI platforms serving elderly',
      'Clinical trial endpoint measurement',
      'Integration with smart speakers and care robots',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-05-PROV',
    relatedIPs: ['04', '09', '14'],
    codeReference: {
      file: 'services/ai/src/services/emotion_detection.py',
      function: 'detect_emotion()',
    },
    estimatedValuation: '$2M-$4M',
  },
  {
    id: '06',
    slug: 'sundowning-detection',
    tier: 2,
    title: 'Time-Window Digital Biomarker for Sundowning',
    shortTitle: 'Sundowning Detection',
    category: 'algorithm',
    headline: 'First digital biomarker for sundowning — late-afternoon cognitive deterioration affecting up to 66% of dementia patients.',
    problemSolved: 'Sundowning causes confusion, agitation, and wandering in the 4–8 PM window. No commercial digital detection system exists.',
    novelMethod: 'Composite risk score: time factor (0.3 if in 16:00-20:00 window) + sleep quality (0-0.2) + light exposure (0-0.1) + agitation (0-0.25) + confusion (0-0.25) + restlessness (0-0.2). Four severity tiers trigger time-sequenced interventions.',
    priorArtDiff: 'No known prior patent for digital sundowning detection. Academic literature describes the phenomenon but no commercial detection system.',
    commercialApplications: [
      'Caregiver alert system for facilities',
      'Home monitoring with family notifications',
      'Clinical trial endpoint for sundowning interventions',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-06-PROV',
    relatedIPs: ['07', '23'],
    codeReference: {
      file: 'packages/cognitive-state/src/SundowningDetector.ts',
      function: 'detectSundowningRisk()',
    },
    estimatedValuation: '$1.5M-$3M',
  },
  {
    id: '07',
    slug: 'composite-biomarker-engine',
    tier: 2,
    title: 'Composite Biomarker Engine with Weight Redistribution',
    shortTitle: 'Composite Biomarker Engine',
    category: 'algorithm',
    headline: 'Five-analyzer biomarker composite with automatic weight redistribution when analyzers lack data, plus medication adherence inversion.',
    problemSolved: 'Individual biomarkers are partial signals. Fixed-weight composites fail when data is missing. Most composite systems omit medication adherence or treat it like other biomarkers.',
    novelMethod: 'Default weights: speech 0.30, cognitive delay 0.25, routine 0.15, sleep 0.15, medication 0.15. Medication score inverted (high adherence → low concern). When an analyzer has insufficient data, its weight is proportionally redistributed. Voting-based trend aggregation.',
    priorArtDiff: 'Evidation Health (US 10,943,696) and BioPrint use fixed weights. No prior art with automatic redistribution + medication inversion.',
    commercialApplications: [
      'Pharma clinical trial digital endpoint',
      'Payer risk stratification',
      'Licensing to remote patient monitoring platforms',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-07-PROV',
    relatedIPs: ['08', '09', '10', '23'],
    codeReference: {
      file: 'packages/biomarker-engine/src/scoring/BiomarkerEngine.ts',
      function: 'computeCompositeBiomarkerScore()',
    },
    estimatedValuation: '$1M-$3M',
  },
  {
    id: '08',
    slug: 'multi-window-decline-detection',
    tier: 2,
    title: 'Multi-Window Longitudinal Decline Detection',
    shortTitle: 'Multi-Window Decline Detection',
    category: 'algorithm',
    headline: 'Detects decline across 7/14/30-day windows with per-biomarker severity deduplication, preventing alert fatigue.',
    problemSolved: 'Single-window detection produces false positives or misses gradual decline. Per-biomarker analysis without deduplication creates alert fatigue for caregivers.',
    novelMethod: 'Analyzes biomarker time series across 7, 14, 30-day windows. Triggers alerts at 10% change threshold. Four severity tiers (low 0.3, moderate 0.5, high 0.7, critical 0.85). Deduplicates by keeping only highest-severity alert per biomarker type.',
    priorArtDiff: 'Apple ECG (US 10,278,630) and generic trend detection don\'t support multi-window + deduplication for cognitive decline.',
    commercialApplications: [
      'Clinical decision support for memory clinics',
      'Caregiver alerting systems',
      'Pharma adverse event detection',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-08-PROV',
    relatedIPs: ['07'],
    codeReference: {
      file: 'packages/biomarker-engine/src/scoring/DeclineDetector.ts',
      function: 'detectDecline()',
    },
    estimatedValuation: '$1M-$2.5M',
  },
  {
    id: '09',
    slug: 'speech-hesitation-biomarker',
    tier: 2,
    title: 'Trimodal Speech Hesitation Biomarker',
    shortTitle: 'Speech Hesitation Biomarker',
    category: 'algorithm',
    headline: 'Three-feature fusion (hesitation, pauses, speech rate) with dynamic threshold for trend detection.',
    problemSolved: 'Single-feature speech biomarkers fail to capture multidimensional dementia speech changes.',
    novelMethod: 'Hesitation count normalized 0-10, pause duration 0-30s, speech rate inverse (normal ≥150 wpm, concerning ≤80 wpm). Composite weights 0.4/0.3/0.3. Dynamic trend threshold: max(10% of mean, 0.5).',
    priorArtDiff: 'Sonde Health (US 10,672,396) and Cogstate (US 8,708,702) use single-feature speech analysis.',
    commercialApplications: [
      'Remote speech screening',
      'Clinical trial speech endpoint',
      'Integration with voice-AI platforms',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-09-PROV',
    relatedIPs: ['05', '07'],
    codeReference: {
      file: 'packages/biomarker-engine/src/analyzers/SpeechBiomarker.ts',
      function: 'analyzeSpeechHesitation()',
    },
    estimatedValuation: '$1M-$2.5M',
  },
  {
    id: '10',
    slug: 'response-time-biomarker',
    tier: 2,
    title: 'Response Time Biomarker with Variance + Trend Penalty',
    shortTitle: 'Response Time Biomarker',
    category: 'algorithm',
    headline: 'Combines base score (5000ms ceiling), variance penalty (0.3 max), and trend penalty (0.2 max) into a unified score.',
    problemSolved: 'Mean response time alone misses inconsistency as stress signal and gradual slowdown over time.',
    novelMethod: 'Score = baseScore + variancePenalty + trendPenalty. Base: min(mean/5000, 1). Variance: min(CV/2, 0.3). Trend: min((slope/mean)*2, 0.2).',
    priorArtDiff: 'Cogstate reaction time and standard chronometric analysis use mean only.',
    commercialApplications: [
      'Digital endpoint for anti-amyloid therapy trials',
      'Screening tool integration',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-10-PROV',
    relatedIPs: ['07'],
    codeReference: {
      file: 'packages/biomarker-engine/src/analyzers/ResponseTimeAnalyzer.ts',
      function: 'analyzeResponseDelay()',
    },
    estimatedValuation: '$800K-$2M',
  },
  {
    id: '11',
    slug: 'decline-predictor-ml',
    tier: 2,
    title: '8-Feature Cognitive Decline Predictor',
    shortTitle: 'Decline Predictor ML',
    category: 'algorithm',
    headline: 'ML pipeline with 8 interpretable features and threshold-based fallback for explainable decline prediction.',
    problemSolved: 'Most ML dementia models use hundreds of features and are not interpretable for FDA SaMD compliance.',
    novelMethod: '8 features: mean score, latest, slope per day, std dev, CV, session frequency, score range, recent trend. Includes threshold-based interpretable fallback and contributing-factor identification.',
    priorArtDiff: 'IBM Watson Health and academic models use large feature vectors without interpretability. No prior art with this specific 8-feature set and fallback.',
    commercialApplications: [
      'Payer risk stratification',
      'Clinical decision support',
      'Licensing to pharma for trial patient selection',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-11-PROV',
    relatedIPs: ['12'],
    codeReference: {
      file: 'services/ai/src/models/decline_predictor.py',
      function: 'predict()',
    },
    estimatedValuation: '$1M-$2.5M',
  },
  {
    id: '12',
    slug: 'algorithm-transparency',
    tier: 2,
    title: 'Algorithm Transparency for FDA SaMD',
    shortTitle: 'Algorithm Transparency',
    category: 'compliance',
    headline: 'Integrated transparency module producing human-readable explanations of scoring and difficulty decisions for FDA audit.',
    problemSolved: 'FDA SaMD requires algorithm transparency. Generic explainability libraries (LIME, SHAP) are not integrated for medical device compliance.',
    novelMethod: 'Produces structured explanations with per-domain interpretations (5 severity tiers), methodology, limitations disclosure, and component-level algorithm version tracking.',
    priorArtDiff: 'No integrated transparency system for SaMD. LIME/SHAP are libraries, not integrated modules.',
    commercialApplications: [
      'FDA 510(k) submission support',
      'Licensing to other SaMD developers',
      'White-label compliance tooling',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-12-PROV',
    relatedIPs: ['01', '11'],
    codeReference: {
      file: 'packages/cognitive-engine/src/transparency.ts',
      function: 'explainScore()',
    },
    estimatedValuation: '$700K-$2M',
  },
  {
    id: '13',
    slug: 'post-market-surveillance',
    tier: 3,
    title: 'Automated Post-Market Surveillance with Drift Detection',
    shortTitle: 'Post-Market Surveillance',
    category: 'compliance',
    headline: 'FDA SaMD post-market surveillance with Pearson-correlation drift detection and multi-source complaint categorization.',
    problemSolved: 'Manual post-market surveillance is labor-intensive and inconsistent; no integrated automated systems exist.',
    novelMethod: 'Pearson correlation monitoring; 4-tier drift (none/mild/moderate/significant) by bias thresholds 0.1/0.2/0.4; complaint intake from 5 sources across 6 categories; p95 alert latency tracking.',
    priorArtDiff: 'FDA MedWatch and Cogstate surveillance are manual. No automated drift + complaint integration.',
    commercialApplications: [
      'White-label to SaMD developers',
      'Regulatory submission component',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-13-PROV',
    relatedIPs: ['12'],
    codeReference: {
      file: 'services/api/src/services/postMarketSurveillance.ts',
      function: 'detectDrift()',
    },
    estimatedValuation: '$500K-$1.5M',
  },
  {
    id: '14',
    slug: 'voice-companion-system',
    tier: 3,
    title: 'Voice Companion System for Dementia Care',
    shortTitle: 'Voice Companion System',
    category: 'system',
    headline: 'Family voice cloning + inactivity prompts + mood-modulated prosody + natural pause insertion.',
    problemSolved: 'Voice cloning exists commercially but is not integrated into therapeutic protocols for dementia care.',
    novelMethod: 'Message introduction protocol (companion → pause → cloned voice); per-person unique pitch/rate; 30s+ inactivity detection with warm prompts; mood-modulated prosody (celebrate +5% rate, calm -15% rate).',
    priorArtDiff: 'ElevenLabs/Resemble are ToS not patents. Replika has no dementia therapeutic protocol.',
    commercialApplications: [
      'Licensing to care facility voice systems',
      'Integration with smart speakers for elderly',
      'Pharma adherence support',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-14-PROV',
    relatedIPs: ['05', '19'],
    codeReference: {
      file: 'apps/mobile/src/services/VoiceCloneService.ts',
      function: 'readMessage()',
    },
    estimatedValuation: '$1M-$3M',
  },
  {
    id: '15',
    slug: 'music-therapy-engine',
    tier: 3,
    title: 'Music Therapy Engine with Circadian + Fade-Out',
    shortTitle: 'Music Therapy Engine',
    category: 'system',
    headline: '2-minute gradual fade-out, mood→playlist mapping, circadian time-of-day recommendations.',
    problemSolved: 'Music therapy is evidence-based for dementia but no commercial implementation combines circadian logic with dementia-specific fade-out.',
    novelMethod: '20-step fade over 2 minutes to prevent startle; mood mapping with clinical rationales; circadian recommendations (morning classical, afternoon nature for sundowning prevention, evening familiar).',
    priorArtDiff: 'Music Health (US 11,127,416) lacks circadian + fade-out combination.',
    commercialApplications: [
      'Licensing to music therapy platforms',
      'Integration with smart speakers',
      'Facility programming tool',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-15-PROV',
    relatedIPs: ['06'],
    codeReference: {
      file: 'apps/mobile/src/services/MusicTherapyEngine.ts',
      function: 'setSleepTimer()',
    },
    estimatedValuation: '$500K-$1.5M',
  },
  {
    id: '16',
    slug: 'enforced-dementia-ux',
    tier: 3,
    title: 'Hard-Enforced Dementia-Safe UX Framework',
    shortTitle: 'Enforced Dementia UX',
    category: 'ux',
    headline: 'Component-level enforcement: 24pt font floor, 80×80px button minimum, max 3 choices per screen, WCAG AAA 7:1 contrast.',
    problemSolved: 'WCAG AAA provides guidelines; dementia-specific UX requires architectural enforcement.',
    novelMethod: 'Text primitive auto-coerces fonts to 24pt. Button primitive hardcodes 80×80px minimum. Choice container validates max 3 options. Theme palette guarantees 7:1 contrast.',
    priorArtDiff: 'WCAG and Apple Accessibility are guidelines; no prior framework with architectural enforcement.',
    commercialApplications: [
      'Open-source component library (defensive)',
      'Licensing to healthtech UI systems',
      'Design system certification',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-16-PROV',
    relatedIPs: [],
    codeReference: {
      file: 'packages/ui-components/src/primitives/',
      function: 'enforceFontFloor()',
    },
    estimatedValuation: '$500K-$1.5M',
  },
  {
    id: '17',
    slug: 'multi-tenant-clinical-isolation',
    tier: 3,
    title: 'Multi-Tenant Clinical Data Isolation',
    shortTitle: 'Multi-Tenant Isolation',
    category: 'system',
    headline: 'Three-tier tenant resolution (header→subdomain→JWT) with transparent Prisma middleware query scoping.',
    problemSolved: 'Healthcare multi-tenancy demands stronger isolation than general SaaS patterns.',
    novelMethod: 'Priority resolution + Prisma `$extends()` auto-injection of tenantId WHERE clauses on all reads and mutation scoping. Transparent to application code.',
    priorArtDiff: 'Salesforce (US 7,299,240) and Snowflake use database-level isolation without transparent middleware injection.',
    commercialApplications: [
      'Licensing to hospital SaaS providers',
      'White-label HIPAA-compliant platform',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-17-PROV',
    relatedIPs: [],
    codeReference: {
      file: 'services/api/src/middleware/tenantResolver.ts',
      function: 'tenantResolver()',
    },
    estimatedValuation: '$300K-$1M',
  },
  {
    id: '18',
    slug: 'cfr11-hash-chain-audit',
    tier: 3,
    title: '21 CFR Part 11 Hash-Chain Audit Trail',
    shortTitle: 'CFR Part 11 Audit',
    category: 'compliance',
    headline: 'Tamper-evident audit log via SHA-256 hash chain with CFR-compliant signature meaning field.',
    problemSolved: 'Clinical trial electronic records require tamper evidence; blockchain approaches are over-engineered for this use case.',
    novelMethod: 'SHA-256 hash chain where each entry includes previous hash; signature includes meaning field (approval/review/responsibility). Lightweight and performant vs blockchain.',
    priorArtDiff: 'Blockchain audit systems (multiple patents) are heavier; specific CFR Part 11 application with meaning field is novel.',
    commercialApplications: [
      'Clinical trial electronic data capture (EDC)',
      'Regulatory compliance SaaS',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-18-PROV',
    relatedIPs: ['12', '13'],
    codeReference: {
      file: 'packages/clinical-export/src/CFR11Compliance.ts',
      function: 'generateAuditTrail()',
    },
    estimatedValuation: '$300K-$900K',
  },
  {
    id: '19',
    slug: 'adaptive-response-policies',
    tier: 3,
    title: 'Cognitive State → Response Policy Mapping',
    shortTitle: 'Adaptive Response Policies',
    category: 'system',
    headline: 'Systematic mapping of 7 cognitive states to curated response policies (tone, strategy, guidelines, fallback).',
    problemSolved: 'Adaptive conversational AI for dementia needs explicit state-to-strategy mapping.',
    novelMethod: '7 states × (tone, strategy, 7+ guidelines, fallback template). E.g., CONFUSED → warm tone, identity-reinforcement strategy, 7 guidelines (use name, short sentences, avoid memory recall, etc.).',
    priorArtDiff: 'Replika and Woebot (US 11,087,094) have general adaptive conversation without systematic dementia state mapping.',
    commercialApplications: [
      'Licensing to voice-AI platforms',
      'Chatbot dementia-care plugins',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-19-PROV',
    relatedIPs: ['04', '14'],
    codeReference: {
      file: 'packages/cognitive-state/src/adaptation/ResponsePolicyManager.ts',
      function: 'getAdaptiveResponse()',
    },
    estimatedValuation: '$400K-$1M',
  },
  {
    id: '20',
    slug: 'wearable-health-processing',
    tier: 3,
    title: 'Wearable Health Signal Processing',
    shortTitle: 'Wearable Signal Processing',
    category: 'system',
    headline: 'HRV (time+frequency+nonlinear), sleep stages with cycle detection, sigma-based anomaly detection vs patient baselines.',
    problemSolved: 'Generic wearable processing misses dementia-specific health anomaly patterns.',
    novelMethod: 'Full HRV suite (SDNN, RMSSD, PNN50, LF/HF, Poincare SD1/SD2); sleep stage + cycle + 0-100 quality score; sigma-deviation anomaly detection with 3σ critical, 2σ warning.',
    priorArtDiff: 'Apple HealthKit, Fitbit, Polar HRV patents exist; dementia-specific integration is novel.',
    commercialApplications: [
      'Integration with Apple Watch, Fitbit dementia programs',
      'Licensing to remote patient monitoring',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-20-PROV',
    relatedIPs: ['07', '23'],
    codeReference: {
      file: 'apps/mobile/src/services/wearables/WearableDataProcessor.ts',
      function: 'analyzeHRV()',
    },
    estimatedValuation: '$300K-$900K',
  },
  {
    id: '21',
    slug: 'fhir-dementia-extensions',
    tier: 3,
    title: 'FHIR R4 Extensions for Dementia Monitoring',
    shortTitle: 'FHIR Dementia Extensions',
    category: 'clinical',
    headline: '5 custom FHIR extensions + SNOMED CT mapping for dementia subtypes.',
    problemSolved: 'Standard FHIR R4 lacks extensions for cognitive staging, biomarker confidence, risk prediction, decline rate, and session engagement.',
    novelMethod: 'Custom URIs under gentlereminder.health/fhir/StructureDefinition/ for 5 extensions plus direct SNOMED CT codes for Alzheimer\'s (26929004), vascular (429998004), Lewy body (80098002), frontotemporal (73768007), mixed (75543006), MCI (386805003).',
    priorArtDiff: 'HL7 FHIR is public standard; Epic and Cerner have proprietary extensions for other domains.',
    commercialApplications: [
      'Contribution to FHIR standard',
      'Licensing to EHR integrators',
      'Pharma data exchange',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-21-PROV',
    relatedIPs: [],
    codeReference: {
      file: 'packages/fhir/src/ExtensionHandler.ts',
      function: 'applyExtension()',
    },
    estimatedValuation: '$200K-$700K',
  },
  {
    id: '22',
    slug: 'pure-ts-statistical-engine',
    tier: 3,
    title: 'Pure TypeScript Clinical Trial Statistical Engine',
    shortTitle: 'Pure TS Statistics',
    category: 'system',
    headline: 'Zero-dependency paired t-test, Wilcoxon, Cohen\'s d, CI — Cornish-Fisher and Lanczos approximations.',
    problemSolved: 'Embedded clinical trial analytics require reproducible statistical computation without external libraries.',
    novelMethod: 'Pure TypeScript implementation of paired t-test (incomplete beta via continued fractions), Wilcoxon (normal approximation), Cohen\'s d, CIs (Cornish-Fisher), Lanczos log-gamma. Deterministic.',
    priorArtDiff: 'Open-source libraries exist (jStat, simple-statistics); integrated clinical trial package is novel.',
    commercialApplications: [
      'Embedded clinical trial EDC',
      'Licensing to research platforms',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-22-PROV',
    relatedIPs: [],
    codeReference: {
      file: 'packages/clinical-export/src/StatisticalAnalysis.ts',
      function: 'pairedTTest()',
    },
    estimatedValuation: '$200K-$600K',
  },
  {
    id: '23',
    slug: 'circadian-biomarkers',
    tier: 3,
    title: 'Circadian Biomarkers (Sleep + Routine)',
    shortTitle: 'Circadian Biomarkers',
    category: 'algorithm',
    headline: 'Sleep irregularity and routine disruption biomarkers with midnight-discontinuity-aware bedtime normalization.',
    problemSolved: 'Naive bedtime computations treat 23:30 → 00:30 as 23-hour shift instead of 1-hour. Existing wearable platforms miss this.',
    novelMethod: 'Sleep irregularity: 0.35 bedtime std + 0.35 wake std + 0.30 awakenings (each capped). Routine disruption: 0.6 first-activity std + 0.4 meal-time std. Novel midnight normalization shifts early-AM times by 24h.',
    priorArtDiff: 'Fitbit and Apple sleep tracking exist; specific normalization and dementia-applied composite is novel.',
    commercialApplications: [
      'Integration with wearable platforms',
      'Clinical trial sleep endpoint',
    ],
    filingStatus: 'draft',
    filingDocket: 'GR-23-PROV',
    relatedIPs: ['06', '07'],
    codeReference: {
      file: 'packages/biomarker-engine/src/analyzers/SleepAnalyzer.ts',
      function: 'analyzeSleepIrregularity()',
    },
    estimatedValuation: '$300K-$900K',
  },
];

export const PORTFOLIO_STATS = {
  totalIPs: IP_PORTFOLIO.length,
  tier1Count: IP_PORTFOLIO.filter((ip) => ip.tier === 1).length,
  tier2Count: IP_PORTFOLIO.filter((ip) => ip.tier === 2).length,
  tier3Count: IP_PORTFOLIO.filter((ip) => ip.tier === 3).length,
  totalFilingCost: IP_PORTFOLIO.length * 300, // micro-entity
  estimatedPortfolioValueLow: '$22M',
  estimatedPortfolioValueHigh: '$56M',
};

export function getIPBySlug(slug: string): IPEntry | undefined {
  return IP_PORTFOLIO.find((ip) => ip.slug === slug);
}

export function getIPsByTier(tier: IPTier): IPEntry[] {
  return IP_PORTFOLIO.filter((ip) => ip.tier === tier);
}

export function getIPsByCategory(category: IPCategory): IPEntry[] {
  return IP_PORTFOLIO.filter((ip) => ip.category === category);
}
